version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: make circleci
      - run:
          name: Build
          command: make build
      - store_artifacts:
          path: build
      - deploy:
          name: Deploy website
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              mv .dockerignore .dockerignore-repo
              docker run -v /home/circleci/.ssh:/tmp/ssh -v $PWD:/work -e MASTER=$MASTER -e TAG=$TAG gliderlabs/pagebuilder deploy "build $CIRCLE_BUILD_NUM"
              mv .dockerignore-repo .dockerignore
            fi
      - deploy:
          name: Deploy beta channel
          command: |
            if [[ "$CIRCLE_BRANCH" == "release" ]]; then
              make release
            fi
