FROM gliderlabs/alpine:3.3
CMD ["/bin/registrator"]

ENV GOPATH /go
RUN apk-install build-base go git mercurial
COPY . /go/src/github.com/gliderlabs/registrator
WORKDIR /go/src/github.com/gliderlabs/registrator
RUN go get -t
WORKDIR bridge
RUN go get -t
RUN go test -v
